listening-port=8302
tls-listening-port=0
listening-ip=0.0.0.0
relay-ip=196.188.249.48
external-ip=196.188.249.48
min-port=8303
max-port=8320
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=63d52d481dba9abfcc08f131c1fe8467ee5dbcaf224d67a1
realm=x.decentral.technology
no-cli
no-tls
no-dtls
log-file=stdout
