x.decentral.technology {
	reverse_proxy 127.0.0.1:8300 {
		header_up Host {host}
		header_up X-Real-IP {remote_host}
		header_up X-Forwarded-Proto {scheme}
	}
}

docs.x.decentral.technology {
	reverse_proxy /cool/*/ws 127.0.0.1:8301 {
		header_up Host {host}
		flush_interval -1
	}
	reverse_proxy /cool/adminws 127.0.0.1:8301 {
		header_up Host {host}
		flush_interval -1
	}
	reverse_proxy 127.0.0.1:8301 {
		header_up Host {host}
	}
}

whiteboard.x.decentral.technology {
	reverse_proxy 127.0.0.1:8303 {
		header_up Host {host}
		header_up X-Real-IP {remote_host}
		header_up X-Forwarded-Proto {scheme}
		flush_interval -1
	}
}
