x.decentral.technology {
	reverse_proxy 127.0.0.1:8300 {
		header_up Host {host}
		header_up X-Real-IP {remote_host}
		header_up X-Forwarded-Proto {scheme}
	}
}

docs.x.decentral.technology {
	reverse_proxy 127.0.0.1:8301 {
		header_up Host {host}
		header_up X-Forwarded-Proto {scheme}
	}
}
